version: "0.0.1"

services:
  be-compose:
    image: ngynbao/cyber_media
    container_name: con_compose_media
    ports:
      - "3070:3069"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRE=${ACCESS_TOKEN_EXPIRE}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRE=${REFRESH_TOKEN_EXPIRE}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
    depends_on:
      - db-compose
    command: ["npm", "run", "start"]

  db-compose:
    image: mysql
    container_name: con_mysql_media
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
