#name of ci
name: CI_DOCKER

#chạy khi nào
on:
  push:
    branches: ["main"]

#chạy công việc
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Đăng nhập vào docker
        run: docker login -u ngynbao -p ${{secrets.DOCKER_TOKEN}}

      - name: Build image
        run: docker build -t ngynbao/cyber_media:latest .

      - name: Push to DockerHub
        run: docker push ngynbao/cyber_media:latest
